unless defined?(AWS_ACCESS_KEY_ID)
  AWS_ACCESS_KEY_ID = ENV['AWS_ACCESS_KEY_ID']
  AWS_SECRET_ACCESS_KEY = ENV['AWS_SECRET_ACCESS_KEY']
  AWS_BUCKET_NAME = ENV['AWS_BUCKET_NAME']

  raise "Missing AWS_ACCESS_KEY_ID" unless AWS_ACCESS_KEY_ID
  raise "Missing AWS_SECRET_ACCESS_KEY" unless AWS_SECRET_ACCESS_KEY
  raise "Missing AWS_BUCKET_NAME" unless AWS_BUCKET_NAME
end

